const Discord = require('discord.js')
const lib = req
const client = new Discord.Client()
const { Kayn, REGIONS } = require('kayn')
const kayn = Kayn('RGAPI-c1814a16-a273-49b2-a8f4-06ca281f5a33')({
    region: REGIONS.BRAZIL,
    apiURLPrefix: 'https://%s.api.riotgames.com',
    locale: 'pt-BR',
    debugOptions: {
        isEnabled: true,
        showKey: false,
    },
    requestOptions: {
        shouldRetry: true,
        numberOfRetriesBeforeAbort: 3,
        delayBeforeRetry: 1000,
        burst: false,
        shouldExitOn403: false,
    },
    cacheOptions: {
        cache: null,
        timeToLives: {
            useDefault: false,
            byGroup: {},
            byMethod: {},
        },
    },
})

exports.run = async (client, message, args) => {

    const emojiList = client.emojis.get("624323979619991582")
    const arrox = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Aatrox')
    .setThumbnail('https://i.imgur.com/9ML0ruQ.png')
    .addField('**Vida:**', '580 (+90 por nível)', true)
    .addField('**Dano de Ataque:**', '60 (+5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '345' ,true)
    .addField('**Armadura:**', '38 (+3.25 por nível)', true)
    .addField('**Regeneração de vida:**', '3 (+1 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://i.imgur.com/cGxClRZ.jpg')

    const ahri = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Ahri')
    .setThumbnail('https://i.imgur.com/ne94Wkr.png')
    .addField('**Vida:**', '526 (+92 por nível)', true)
    .addField('**Dano de Ataque:**', '53.04 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2% por nível)', true)
    .addField('**Velocidade Movimento:**', '330' ,true)
    .addField('**Armadura:**', '20.88 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '6.5 (+0.6 por nível)', true)
    .addField('**Resistência Mágica:**', '30 (+0.5 por nível)\n\nPode ser obtido em baús hextech ou comprando na loja', true)
    .setImage('https://i.imgur.com/X4t8o0f.jpg')
    
    
    const akali = new Discord.RichEmbed()
    .setColor('#4F4F4F')
    .setAuthor('Akali')
    .setThumbnail('https://i.imgur.com/eqndQTi.png')
    .addField('**Vida:**', '575 (+95 por nível)', true)
    .addField('**Dano de Ataque:**', '62.4 (+3.3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3.2% por nível)', true)
    .addField('**Velocidade Movimento:**', '345' ,true)
    .addField('**Armadura:**', '23 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '8 (+0.5 por nível)', true)
    .addField('**Resistência Mágica:**', '37 (+1.25 por nível)\n\nPode ser obtida em baús hextech ou comprando na loja', true)
    .setImage('https://i.imgur.com/yaKts5H.jpg')

    const alistar = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Alistar')
    .setThumbnail('https://i.imgur.com/AnpHBdW.png')
    .addField('**Vida:**', '573.36 (+106 por nível)', true)
    .addField('**Dano de Ataque:**', '61.1116 (+3.62 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.125% por nível)', true)
    .addField('**Velocidade Movimento:**', '330' ,true)
    .addField('**Armadura:**', '44 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '8.5 (+0.85 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 1350 Essência azul ou por 585 de ${emojiList}`, true)
    .setImage('https://i.imgur.com/pi14Jd9.jpg')
    
    const amumu = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Amumu, a Múmia Triste')
    .setThumbnail('https://i.imgur.com/WiQGuqT.png')
    .addField('**Vida:**', '613.12 (+84 por nível)', true)
    .addField('**Dano de Ataque:**', '53.38 (+3.8 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.18% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '33 (+3.8 por nível)', true)
    .addField('**Regeneração de vida:**', '9 (+0.85 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 450 Essência azul ou por 260 de ${emojiList}`, true)
    .setImage('https://i.imgur.com/fja1B5g.jpg')

    const anivia = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Anivia, a Criofênix')
    .setThumbnail('https://i.imgur.com/4mxpsH5.png')
    .addField('**Vida:**', '480 (+82 por nível)', true)
    .addField('**Dano de Ataque:**', '51.376 (+3.2 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.68% por nível)', true)
    .addField('**Velocidade Movimento:**', '325' ,true)
    .addField('**Armadura:**', '21.22 (+4 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 3150 Essência azul ou por 790 de ${emojiList}`, true)
    .setImage('https://i.imgur.com/s6BNeIz.jpg')

    const annie = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Annie, a Criança Sombria')
    .setThumbnail('https://i.imgur.com/sSX8j8W.png')
    .addField('**Vida:**', '524 (+88 por nível)', true)
    .addField('**Dano de Ataque:**', '50.41 (+2.625 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.36% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '19.22 (+4 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 450 Essência azul ou por 260 de ${emojiList}`, true)
    .setImage('https://i.imgur.com/HiKwuPc.jpg')

    const ashe = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Ashe, a Arqueira do Gelo')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Ashe.png')
    .addField('**Vida:**', '539 (+85 por nível)', true)
    .addField('**Dano de Ataque:**', '61 (+2.96 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3.33% por nível)', true)
    .addField('**Velocidade Movimento:**', '325' ,true)
    .addField('**Armadura:**', '26 (+3.4 por nível)', true)
    .addField('**Regeneração de vida:**', '3.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 450 Essência azul ou por 260 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg')

    const AurelionSol = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Aurelion Sol, o Forjador de Estrelas')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/AurelionSol.png')
    .addField('**Vida:**', '575 (+92 por nível)', true)
    .addField('**Dano de Ataque:**', '57 (+3.2 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.36% por nível)', true)
    .addField('**Velocidade Movimento:**', '325' ,true)
    .addField('**Armadura:**', '19 (+3.6 por nível)', true)
    .addField('**Regeneração de vida:**', '7 (+0.6 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg')

    const azir = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Azir, o Imperador das Areias')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Azir.png')
    .addField('**Vida:**', '552 (+92 por nível)', true)
    .addField('**Dano de Ataque:**', '52 (+2.8 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '19.04 (+3 por nível)', true)
    .addField('**Regeneração de vida:**', '7 (+0.75 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg')

    const bardo = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Bardo, o Protetor Andarilho')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Bard.png')
    .addField('**Vida:**', '575 (+89 por nível)', true)
    .addField('**Dano de Ataque:**', '52 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2% por nível)', true)
    .addField('**Velocidade Movimento:**', '330' ,true)
    .addField('**Armadura:**', '34 (+4 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg')

    const Blitzcrank = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Blitzcrank, o Grande Golem a Vapor')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Blitzcrank.png')
    .addField('**Vida:**', '582.6 (+95 por nível)', true)
    .addField('**Dano de Ataque:**', '61.54 (+3.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.13% por nível)', true)
    .addField('**Velocidade Movimento:**', '325' ,true)
    .addField('**Armadura:**', '44 (+4 por nível)', true)
    .addField('**Regeneração de vida:**', '8.5 (+0.75 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 3150 Essência azul ou por 790 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg')

    const Brand = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Brand, a Vingança Flamejante')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Brand.png')
    .addField('**Vida:**', '519.68 (+88 por nível)', true)
    .addField('**Dano de Ataque:**', '57.04 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.36% por nível)', true)
    .addField('**Velocidade Movimento:**', '340' ,true)
    .addField('**Armadura:**', '21.88 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg')

    const Braum = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Braum, o Coração de Freljord')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Braum.png')
    .addField('**Vida:**', '540 (+87 por nível)', true)
    .addField('**Dano de Ataque:**', '55.376 (+3.2 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '47 (+4 por nível)', true)
    .addField('**Regeneração de vida:**', '8 (+1 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg')

    const caitlyn = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Caitlyn, a Xerife de Piltover')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Caitlyn.png')
    .addField('**Vida:**', '481 (+91 por nível)', true)
    .addField('**Dano de Ataque:**', '62 (+2.88 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+4% por nível)', true)
    .addField('**Velocidade Movimento:**', '325' ,true)
    .addField('**Armadura:**', '28 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '3.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg')

    const Camille = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Camille, a Sombra de Aço')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Camille.png')
    .addField('**Vida:**', '575.6 (+85 por nível)', true)
    .addField('**Dano de Ataque:**', '68 (+3.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '340' ,true)
    .addField('**Armadura:**', '35 (+3.8 por nível)', true)
    .addField('**Regeneração de vida:**', '8.5 (+0.8 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_0.jpg')

    const Cassiopeia = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Cassiopeia, o Abraço da Serpente')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Cassiopeia.png')
    .addField('**Vida:**', '575 (+90 por nível)', true)
    .addField('**Dano de Ataque:**', '53 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '328' ,true)
    .addField('**Armadura:**', '20 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.5 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_0.jpg')

    const ChoGath = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Cho´Gath, o Terror do Vazio')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Chogath.png')
    .addField('**Vida:**', '574.4 (+80 por nível)', true)
    .addField('**Dano de Ataque:**', '69 (+4.2 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.44% por nível)', true)
    .addField('**Velocidade Movimento:**', '345' ,true)
    .addField('**Armadura:**', '38 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '9 (+0.85 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 1350 Essência azul ou por 585 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_0.jpg')

    const corki = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Corki, o Bombardeiro Ousado')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Corki.png')
    .addField('**Vida:**', '518 (+87 por nível)', true)
    .addField('**Dano de Ataque:**', '55 (+2.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.3% por nível)', true)
    .addField('**Velocidade Movimento:**', '325' ,true)
    .addField('**Armadura:**', '28 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 3150 Essência azul ou por 790 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg')

    const darius = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Darius, a Mão de Noxus')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Darius.png')
    .addField('**Vida:**', '582.24 (+100 por nível)', true)
    .addField('**Dano de Ataque:**', '64 (+5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1% por nível)', true)
    .addField('**Velocidade Movimento:**', '340' ,true)
    .addField('**Armadura:**', '39 (+4 por nível)', true)
    .addField('**Regeneração de vida:**', '10 (+0.95 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_0.jpg')
    
    const diana = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Diana, o Escárnio da Lua')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Diana.png')
    .addField('**Vida:**', '594 (+95 por nível)', true)
    .addField('**Dano de Ataque:**', '53.04 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.25% por nível)', true)
    .addField('**Velocidade Movimento:**', '345' ,true)
    .addField('**Armadura:**', '31 (+3.6 por nível)', true)
    .addField('**Regeneração de vida:**', '7.5 (+0.85 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_0.jpg')

    const DrMundo = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Dr. Mundo, o Louco de Zaun')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/DrMundo.png')
    .addField('**Vida:**', '582.52 (+89 por nível)', true)
    .addField('**Dano de Ataque:**', '61.27 (+3.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.8% por nível)', true)
    .addField('**Velocidade Movimento:**', '345' ,true)
    .addField('**Armadura:**', '36 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '8 (+0.75 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 450 Essência azul ou por 260 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_0.jpg')

    const Draven = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Draven, o Carrasco de Noxus')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Draven.png')
    .addField('**Vida:**', '574 (+88 por nível)', true)
    .addField('**Dano de Ataque:**', '60 (+3.61 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.7% por nível)', true)
    .addField('**Velocidade Movimento:**', '330' ,true)
    .addField('**Armadura:**', '29 (+3.3 por nível)', true)
    .addField('**Regeneração de vida:**', '3.75 (+0.7 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_0.jpg')

    const Ekko = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Ekko, o Rapaz que Estilhaçou o Tempo')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Ekko.png')
    .addField('**Vida:**', '585 (+85 por nível)', true)
    .addField('**Dano de Ataque:**', '58 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3.3% por nível)', true)
    .addField('**Velocidade Movimento:**', '340' ,true)
    .addField('**Armadura:**', '32 (+3 por nível)', true)
    .addField('**Regeneração de vida:**', '9 (+0.9 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_0.jpg')

    const Elise = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Elise, a Aranha Rainha')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Elise.png')
    .addField('**Vida:**', '534 (+93 por nível)', true)
    .addField('**Dano de Ataque:**', '55 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.75% por nível)', true)
    .addField('**Velocidade Movimento:**', '330' ,true)
    .addField('**Armadura:**', '27 (+3.35 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.6 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_0.jpg')

    const Evelynn = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Evelynn, Abraço da Agonia')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Evelynn.png')
    .addField('**Vida:**', '572 (+84 por nível)', true)
    .addField('**Dano de Ataque:**', '61 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.1% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '37 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '8.5 (+0.75 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 1350 Essência azul ou por 585 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Evelynn_0.jpg')

    const Ezreal = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Ezreal, o Explorador Pródigo')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Ezreal.png')
    .addField('**Vida:**', '491 (+86 por nível)', true)
    .addField('**Dano de Ataque:**', '60 (+2.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '325' ,true)
    .addField('**Armadura:**', '22 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '4 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg')

    const Fiddlesticks = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Fiddlesticks, o Mensageiro da Morte')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Fiddlesticks.png')
    .addField('**Vida:**', '524.4 (+80 por nível)', true)
    .addField('**Dano de Ataque:**', '48.36 (+2.625 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.11% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '30 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.6 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 1350 Essência azul ou por 585 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg')

    const Fiora = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Fiora, a Grande Duelista')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Fiora.png')
    .addField('**Vida:**', '550 (+85 por nível)', true)
    .addField('**Dano de Ataque:**', '68 (+3.3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3.2% por nível)', true)
    .addField('**Velocidade Movimento:**', '345' ,true)
    .addField('**Armadura:**', '33 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '8.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiora_0.jpg')

    const Fizz = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Fizz, o Trapaceiro das Marés')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Fizz.png')
    .addField('**Vida:**', '570 (+98 por nível)', true)
    .addField('**Dano de Ataque:**', '58.04 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3.1% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '22.412 (+3.4 por nível)', true)
    .addField('**Regeneração de vida:**', '8 (+0.7 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fizz_0.jpg')

    const Galio = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Galio, o Trapaceiro das Marés')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Galio.png')
    .addField('**Vida:**', '562 (+112 por nível)', true)
    .addField('**Dano de Ataque:**', '59 (+3.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '24 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '8 (+0.8 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 3150 Essência azul ou por 790 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg')

    const Gangplank = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Gangplank, o Terror dos Doze Mares')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Gangplank.png')
    .addField('**Vida:**', '540 (+82 por nível)', true)
    .addField('**Dano de Ataque:**', '64 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3.2% por nível)', true)
    .addField('**Velocidade Movimento:**', '345' ,true)
    .addField('**Armadura:**', '35 (+3 por nível)', true)
    .addField('**Regeneração de vida:**', '6 (+0.6 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 3150 Essência azul ou por 790 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gangplank_0.jpg')

    const Garen = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Garen, o Poder de Demacia')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Garen.png')
    .addField('**Vida:**', '616.28 (+84.25 por nível)', true)
    .addField('**Dano de Ataque:**', '66 (+4.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.9% por nível)', true)
    .addField('**Velocidade Movimento:**', '340' ,true)
    .addField('**Armadura:**', '36 (+3 por nível)', true)
    .addField('**Regeneração de vida:**', '8 (+0.5 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 450 Essência azul ou por 260 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_0.jpg')

    const Gnar = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Gnar, o Yordle Pré-Histórico')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Gnar.png')
    .addField('**Vida:**', '510 (+65 por nível)', true)
    .addField('**Dano de Ataque:**', '59 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+6% por nível)', true)
    .addField('**Velocidade Movimento:**', '325' ,true)
    .addField('**Armadura:**', '32 (+2.5 por nível)', true)
    .addField('**Regeneração de vida:**', '4.5 (+1.75 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gnar_0.jpg')

    const Gragas = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Gragas, o Badernista')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Gragas.png')
    .addField('**Vida:**', '600 (+95 por nível)', true)
    .addField('**Dano de Ataque:**', '64 (+3.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.05% por nível)', true)
    .addField('**Velocidade Movimento:**', '330' ,true)
    .addField('**Armadura:**', '35 (+3.6 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.5 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 3150 Essência azul ou por 790 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gragas_0.jpg')

    const Graves = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Graves, o Foragido')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Graves.png')
    .addField('**Vida:**', '551.12 (+92 por nível)', true)
    .addField('**Dano de Ataque:**', '66 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.6% por nível)', true)
    .addField('**Velocidade Movimento:**', '340' ,true)
    .addField('**Armadura:**', '33 (+3.4 por nível)', true)
    .addField('**Regeneração de vida:**', '8 (+0.7 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+1 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Graves_0.jpg')

    const Hecarim = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Hecarim, a Sombra da Guerra')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Hecarim.png')
    .addField('**Vida:**', '580 (+90 por nível)', true)
    .addField('**Dano de Ataque:**', '66 (+3.2 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '345' ,true)
    .addField('**Armadura:**', '36 (+4 por nível)', true)
    .addField('**Regeneração de vida:**', '7 (+0.75 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hecarim_0.jpg')

    const Heimerdinger = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Heimerdinger, o Inventor Idolatrado')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Heimerdinger.png')
    .addField('**Vida:**', '488 (+87 por nível)', true)
    .addField('**Dano de Ataque:**', '55.536 (+2.7 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+1.36% por nível)', true)
    .addField('**Velocidade Movimento:**', '340' ,true)
    .addField('**Armadura:**', '19.04 (+3 por nível)', true)
    .addField('**Regeneração de vida:**', '7 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 3150 Essência azul ou por 790 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg')

    const Illaoi = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Illaoi, a Sacerdotisa Cráquem')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Illaoi.png')
    .addField('**Vida:**', '585.6 (+95 por nível)', true)
    .addField('**Dano de Ataque:**', '68 (+5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '340' ,true)
    .addField('**Armadura:**', '35 (+3.8 por nível)', true)
    .addField('**Regeneração de vida:**', '9.5 (+0.8 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Illaoi_0.jpg')

    const Irelia = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Irelia, a Dançarina das Lâminas')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Irelia.png')
    .addField('**Vida:**', '580 (+95 por nível)', true)
    .addField('**Dano de Ataque:**', '63 (+4 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.5% por nível)', true)
    .addField('**Velocidade Movimento:**', '335' ,true)
    .addField('**Armadura:**', '36 (+3 por nível)', true)
    .addField('**Regeneração de vida:**', '8.5 (+0.85 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 4800 Essência azul ou por 880 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Irelia_0.jpg')

    const Ivern = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Ivern, o Pai do Verde')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Ivern.png')
    .addField('**Vida:**', '585 (+95 por nível)', true)
    .addField('**Dano de Ataque:**', '50 (+3 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+3.4% por nível)', true)
    .addField('**Velocidade Movimento:**', '330' ,true)
    .addField('**Armadura:**', '27 (+3.5 por nível)', true)
    .addField('**Regeneração de vida:**', '7 (+0.85 por nível)', true)
    .addField('**Resistência Mágica:**\n', `32.1 (+1.25 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_0.jpg')

    const Janna = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Janna, a Fúria da Tormenta')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/Janna.png')
    .addField('**Vida:**', '500 (+70 por nível)', true)
    .addField('**Dano de Ataque:**', '46 (+1.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.95% por nível)', true)
    .addField('**Velocidade Movimento:**', '315' ,true)
    .addField('**Armadura:**', '28 (+3.8 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_0.jpg')
    
     const Jarvan4 = new Discord.RichEmbed()
    .setColor('#0099ff')
    .setAuthor('Jarvan IV, o exemplo de demacia')
    .setThumbnail('https://ddragon.leagueoflegends.com/cdn/9.18.1/img/champion/JarvanIV.png')
    .addField('**Vida:**', '500 (+70 por nível)', true)
    .addField('**Dano de Ataque:**', '46 (+1.5 por nível)', true)
    .addField('**Velocidade de ataque:**', 'NaN (+2.95% por nível)', true)
    .addField('**Velocidade Movimento:**', '315' ,true)
    .addField('**Armadura:**', '28 (+3.8 por nível)', true)
    .addField('**Regeneração de vida:**', '5.5 (+0.55 por nível)', true)
    .addField('**Resistência Mágica:**\n', `30 (+0.5 por nível)\n\nPode ser obtido em baús hextecs ou comprando na loja por 6300 Essência azul ou por 975 de ${emojiList}`, true)
    .setImage('https://ddragon.leagueoflegends.com/cdn/img/champion/splash/JarvanIV_0.jpg')
    
    
    if(args[0]=='aatrox') message.channel.send(arrox)
    if(args[0]== "ahri") message.channel.send(ahri)   
    if(args[0]== 'akali') message.channel.send(akali)
    if(args[0]== 'alistar') message.channel.send(alistar)
    if(args[0]== 'amumu') message.channel.send(amumu)
    if(args[0]== 'anivia') message.channel.send(anivia)
    if(args[0]== 'annie') message.channel.send(annie)
    if(args[0]== 'ashe') message.channel.send(ashe)
    if(args[0]== 'aurelion') message.channel.send(AurelionSol)
    if(args[0]== 'azir') message.channel.send(azir)
    if(args[0]== 'bardo') message.channel.send(bardo)
    if(args[0]== 'blitzcrank') message.channel.send(Blitzcrank)
    if(args[0]== 'brand') message.channel.send(Brand)
    if(args[0]== 'braum') message.channel.send(Braum)
    if(args[0]== 'caitlyn') message.channel.send(caitlyn)
    if(args[0]== 'camille') message.channel.send(Camille)
    if(args[0]== 'cassiopeia') message.channel.send(Cassiopeia)
    if(args[0]== 'chogath') message.channel.send(ChoGath)
    if(args[0]== 'corki') message.channel.send(corki)
    if(args[0]== 'darius') message.channel.send(darius)
    if(args[0]== 'diana') message.channel.send(diana)
    if(args[0]== 'drmundo') message.channel.send(DrMundo)
    if(args[0]== 'draven') message.channel.send(Draven)
    if(args[0]== 'ekko') message.channel.send(Ekko)
    if(args[0]== 'elise') message.channel.send(Elise)   
    if(args[0]== 'evelynn') message.channel.send(Evelynn)
    if(args[0]== 'ezreal') message.channel.send(Ezreal)
    if(args[0]== 'fiddlesticks') message.channel.send(Fiddlesticks)
    if(args[0]== 'fiora') message.channel.send(Fiora)
    if(args[0]== 'fizz') message.channel.send(Fizz)
    if(args[0]== 'galio') message.channel.send(Galio)
    if(args[0]== 'gangplank') message.channel.send(Gangplank)
    if(args[0]== 'garen') message.channel.send(Garen)
    if(args[0]== 'gnar') message.channel.send(Gnar)
    if(args[0]== 'gragas') message.channel.send(Gragas)
    if(args[0]== 'graves') message.channel.send(Graves)
    if(args[0]== 'hecarim') message.channel.send(Hecarim)
    if(args[0]== 'heimerdinger') message.channel.send(Heimerdinger)
    if(args[0]== 'illaoi') message.channel.send(Illaoi)
    if(args[0]== 'irelia') message.channel.send(Irelia)
    if(args[0]== 'ivern') message.channel.send(Ivern)
    if(args[0]== 'janna') message.channel.send(Janna)
    if(args[0]== 'jarvan') message.channel.send(Jarvan4)

    /*if(args[0]){
        kayn.Summoner.by.name(`${args[0]}`)
        .region(REGIONS.BRAZIL)
        .callback(function(err, summoner) {
            console.log(summoner)
            const embed = new Discord.RichEmbed()
            .setColor('#0099ff')
            .setAuthor(message.author.username)
            .addField('**Level do invocador:**', summoner['summonerLevel'])
            .addField('**Nome do invocador: **', summoner['name'])
            .addField('**Id da conta do invocador:** ', summoner['accountId'])
            .addField(summoner['profileIconId'])

            message.channel.send(embed)
        })
    }*/
    if(args[0])
    {
        kayn.Summoner.by.name(`${args[0]}`)
        .region(REGIONS.BRAZIL)
        .callback(function(err, summoner) {
            console.log(summoner)
            const embed = new Discord.RichEmbed()
            .setColor('#0099ff')
            .setAuthor(message.author.username)
            .addField('**Level do invocador:**', summoner['summonerLevel'])
            .addField('**Nome do invocador: **', summoner['name'])
            .addField('**Id da conta do invocador:** ', summoner['accountId'])
            .addField(summoner['profileIconId'])

            message.channel.send(embed)
        })
    }
    if(args[0]== 'cham'){
        kayn.DDragon.Champion.list()
        .version('9.18.1') /* Explicit */
        .callback(function(error, champions) {
        console.log(Yasuo['id'])
    })
    }

    if(args[0]){

            console.log(`./dragontail-9.18.1/9.18.1/data/pt-BR/champion/${args[0]}.json`)
           
        }
    
}